# Generated by Django 2.2.3 on 2019-07-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('yhat', models.IntegerField()),
                ('y', models.IntegerField()),
                ('yhat_upper', models.IntegerField()),
                ('yhat_lower', models.IntegerField()),
                ('anomaly', models.FloatField()),
                ('location', models.CharField(max_length=7)),
                ('pred_date', models.DateTimeField()),
                ('indicator', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
